Add e2e test with NPM

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -235,8 +235,69 @@ jobs:
             exit 1
           fi
 
-  test-plugin-auto-install-in-project:
-    name: Test plugin auto-install in existing project
+  # Using `npx datadog-ci` only runs the binary without fetching any package.
+  test-plugin-auto-install-in-project-npm:
+    name: Test plugin auto-install in existing project (NPM)
+    runs-on: ubuntu-latest
+    needs: build-and-test
+    env:
+      FORCE_COLOR: 1
+
+    steps:
+      - name: Install node
+        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
+        with:
+          node-version: 20
+      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
+        with:
+          name: artifacts-20
+          path: artifacts/
+      - name: Create test project
+        run: |
+          echo '{
+            "name": "datadog-ci-plugin-auto-install",
+            "dependencies": {
+              "@datadog/datadog-ci": "file:./artifacts/@datadog-datadog-ci-20.tgz",
+              "@datadog/datadog-ci-base": "file:./artifacts/@datadog-datadog-ci-base-20.tgz"
+            }
+          }' > package.json
+
+          # Use `--legacy-peer-deps` because `overrides` do not work in our case.
+          npm install --legacy-peer-deps
+      - name: Check that AAS plugin is not installed
+        run: |
+          if npx datadog-ci plugin check aas; then
+            echo "Checking for AAS plugin should have failed, but it succeeded"
+            exit 1
+          else
+            echo "Checking for AAS plugin failed as expected"
+            exit 0
+          fi
+      - name: Run AAS command with auto-install
+        run: |
+          output=$(npx datadog-ci aas instrument || true)
+          if echo "$output" | grep "Successfully installed"; then
+            echo "AAS plugin was automatically installed"
+            exit 0
+          else
+            echo "AAS plugin was not automatically installed"
+            echo "Output: $output"
+            exit 1
+          fi
+      - name: Install AAS plugin
+        run: npx datadog-ci plugin install aas
+      - name: Check that AAS plugin is installed
+        run: |
+          if npx datadog-ci plugin check aas; then
+            echo "AAS plugin was successfully installed"
+            exit 0
+          else
+            echo "AAS plugin was not installed"
+            exit 1
+          fi
+
+  test-plugin-auto-install-in-project-yarn:
+    name: Test plugin auto-install in existing project (Yarn)
     runs-on: ubuntu-latest
     needs: build-and-test
     env:
